version: '3'
services:
  postgres-db:
    image: postgres:13.1
    container_name: postgres-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432

  pgadmin-web:
    image: dpage/pgadmin4:4.28
    container_name: pgadmin-web
    restart: always
    depends_on:
      - postgres-db
    links:
      - "postgres-db:postgres-db"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgrestest@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  cp-zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  cp-kafka-1:
    image: confluentinc/cp-kafka:5.3.1
    container_name: cp-kafka-1
    depends_on:
      - cp-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cp-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cp-kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cp-schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    container_name: cp-schema-registry
    depends_on:
      - cp-zookeeper
      - cp-kafka-1
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: cp-zookeeper:2181

  cp-schema-registry-ui:
    image: landoop/schema-registry-ui:0.9.5
    container_name: cp-schema-registry-ui
    depends_on:
      - cp-schema-registry
    ports:
      - 8060:8000
    links:
      - "cp-schema-registry:cp-schema-registry"
    environment:
      SCHEMAREGISTRY_URL: http://cp-schema-registry:8081/
      ALLOW_GLOBAL: 1
      ALLOW_TRANSITIVE: 1
      ALLOW_DELETION: 1
      PROXY: 1

  kafdrop-ui:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop-ui
    hostname: kafdrop-ui
    ports:
      - 9100:9000
    environment:
      KAFKA_BROKERCONNECT: cp-kafka-1:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SCHEMAREGISTRY_CONNECT: http://cp-schema-registry:8081/
    depends_on:
        - cp-schema-registry

networks:
  default:
    driver: bridge